### ISSUE TITLE
plan sorting when LatestJobStartTime is empty

### ISSUE THREAD

**Issue by shaofeng66** [jibutech/backup-saas-client#50]
Problem: when LatestJobStartTime is empty ks cloud will show LatestJobCreationTimestamp instead, but the plan list is sorted by LatestJobStartTime, which make the result looks wired. see below 2021-11-04 17:46:05 is actually LatestJobCreationTimestamp of that item:
![image](https://user-images.githubusercontent.com/88640691/141395484-2191bf96-73a5-4456-877e-253c5dd5c20e.png)

I am adding support of sortBy=status.jobDetail.LatestJobTime, which will sort by a virtual field that constructed from LatestJobStartTime == nil ? LatestJobCreationTimestamp : LatestJobStartTime

**Comment by stoneshi-yunify** [comment]
I don't like binding a specific frontend display need to jibu backend, which lacks flexibility in extending both frontend and backend.

However, we don't have a middleware between jibu backend and ks-cloud frontend (the ks-cloud backend doesn't handle any backup/restore plans and jobs). We considered adding this layer sometimes in the future. For now, the jibu backend is directly connected to ks-cloud frontend, so if other `flexible` ways not work, we have to accept jibu's fix.

I saw the fix is done already, let's go with it. thanks!

**Comment by shaofeng66** [comment]
fixed
